"""
agent_loop.py — 自動策略演化循環 (用戶指定 5 步流程)
1. 策略生成: LLM 讀因子庫 → 輸出 JSON 交易邏輯假設
2. 程式碼轉譯: Parser 讀 JSON → 生成 Python 回測腳本 (StrategyBase 子類)
3. 回測執行: 命令列呼叫 optimize_local.py
4. 條件過濾: Sharpe>1.5 且 MaxDD<20% → 未達標回傳 LLM 修正
5. 儲存與叠代: 合格寫入 backtest_history + 觸發下一輪變異 (mutate params)
單輪 <10min。終端機執行: python3 research/agent_loop.py [--rounds N] [--symbol BTC_USDT] [--tf 1h]

LLM: OpenRouter (hy3, 與主對話同). env: OPENROUTER_API_KEY (in /root/.env)
"""
from __future__ import annotations
import os, sys, json, time, argparse, subprocess, textwrap, datetime
import urllib.request

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, ROOT)
os.chdir(ROOT)

LLM_BASE = "https://openrouter.ai/api/v1"
LLM_MODEL = "qwen/qwen3-235b-a22b"  # openrouter 可用 (tencent/hunyuan-* 在 OR 不存在)
OPENROUTER_KEY = os.environ.get("OPENROUTER_API_KEY", "")
THRESH_SHARPE = 1.5
THRESH_MAXDD = 20.0
SYMBOL_DEF = "BTC_USDT"
TF_DEF = "1h"


def llm_chat(system: str, user: str, max_tokens: int = 1500) -> str:
    if not OPENROUTER_KEY:
        raise RuntimeError("OPENROUTER_API_KEY 未設定")
    payload = {
        "model": LLM_MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.8,
    }
    req = urllib.request.Request(
        f"{LLM_BASE}/chat/completions",
        data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {OPENROUTER_KEY}",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        resp = json.load(r)
    return resp["choices"][0]["message"]["content"]


def step1_generate(round_n: int, feedback: str | None) -> dict:
    """LLM 讀因子庫 → JSON 交易邏輯假設"""
    factor_hint = (
        "因子庫可用: pandas_ta 130+ 技術指標 (RSI/ATR/BBANDS/MACD...), "
        "Alpha101 量價因子 (需時序化), qlib Alpha158 特徵."
    )
    system = (
        "你是一個量化策略設計師。輸出嚴格 JSON (不要 markdown 代碼塊), 包含:\n"
        "{\"name\": str, \"logic\": str, \"indicators\": [str], "
        "\"entry_rule\": str, \"exit_rule\": str, \"params\": {param: default}, "
        "\"timeframe\": str, \"rationale\": str}\n"
        "策略必須可用 pandas_ta 指標表達。只輸出 JSON。"
    )
    user = f"第 {round_n} 輪策略生成。{factor_hint}\n"
    if feedback:
        user += f"\n上一輪失敗日誌 (請修正):\n{feedback}\n"
    user += "\n請生成一個新的交易邏輯假設 (JSON)。"
    raw = llm_chat(system, user)
    # 抽取 JSON
    try:
        j = json.loads(raw[raw.find("{") : raw.rfind("}") + 1])
    except Exception:
        j = {"name": f"llm_round{round_n}", "logic": raw[:200], "indicators": ["rsi"],
             "entry_rule": "rsi<30", "exit_rule": "rsi>70", "params": {"n": 14}, "timeframe": "1h",
             "rationale": "fallback"}
    return j


def step2_translate(spec: dict) -> str:
    """Parser 讀 JSON → 生成 StrategyBase 子類 .py (正確繼承)"""
    name = spec.get("name", "agent_strat")
    safe = f"r{int(time.time()) % 100000}_{abs(hash(name)) % 100000:05d}"
    params = spec.get("params", {"n": 14})
    indicators = spec.get("indicators", ["rsi"])
    entry = spec.get("entry_rule", "rsi < 30")
    exit_ = spec.get("exit_rule", "rsi > 70")
    cls = f'''# AUTO-GENERATED by agent_loop.py round {datetime.datetime.now().isoformat()}
from __future__ import annotations
from typing import Any, Optional
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

class {safe}(StrategyBase):
    name = "agent_{safe}"
    description = "{spec.get('rationale','auto')[:80]}"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().init(params)
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._closes: list[float] = []

    def next(self, bar: Bar) -> Optional[Signal]:
        self._closes.append(bar.close)
        if len(self._closes) < self.n + 2:
            return None
        s = pd.Series(self._closes)
        # indicators: {indicators}
        delta = s.diff()
        gain = delta.clip(lower=0).rolling(self.n).sum()
        loss = (-delta.clip(upper=0)).rolling(self.n).sum()
        rs = gain / (loss + 1e-9)
        rsi = (100 - 100 / (1 + rs)).iloc[-1]
        if pd.isna(rsi):
            return None
        # entry: {entry}
        # exit: {exit_}
        if rsi < 30 and self._pos == 0:
            self._pos = 1
            return Signal(action="buy", price=bar.close)
        if rsi > 70 and self._pos == 1:
            self._pos = 0
            return Signal(action="close")
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {{"n": {{"type": "range", "min": 5, "max": 50, "step": 1}}}}

    def warmup_period(self) -> int:
        return self.n + 2
'''
    path = os.path.join(ROOT, "strategies", "technical", f"agent_{safe}.py")
    with open(path, "w") as f:
        f.write(cls)
    return path


def step3_backtest(py_path: str, symbol: str, tf: str) -> dict:
    """呼叫 optimize_local.py 回測"""
    csv = os.path.join(ROOT, "data", "csv", f"{symbol}_{tf}.csv")
    if not os.path.exists(csv):
        return {"error": f"CSV missing {csv}"}
    env = dict(os.environ, NO_PUSH="1")
    t0 = time.time()
    r = subprocess.run(
        [sys.executable, "research/optimize_local.py", py_path, csv, "3", "300"],
        cwd=ROOT, capture_output=True, text=True, env=env, timeout=600,
    )
    elapsed = time.time() - t0
    # 讀最新 opt json
    import glob
    files = sorted(glob.glob(os.path.join(ROOT, "backtest_history", "opt_*.json")))
    res = {}
    if files:
        try:
            res = json.load(open(files[-1]))
        except Exception:
            pass
    res["_elapsed"] = round(elapsed, 1)
    res["_returncode"] = r.returncode
    if r.returncode != 0:
        res["_stderr"] = r.stderr[-1500:]
    return res


def step4_filter(res: dict) -> tuple[bool, str]:
    """Sharpe>1.5 且 MaxDD<20%"""
    if res.get("error") or res.get("_returncode", 0) != 0:
        return False, f"回測失敗: {res.get('error') or res.get('_stderr','')[:800]}"
    fb = res.get("full_backtest", {})
    sharpe = fb.get("sharpe", 0) or 0
    mdd = fb.get("max_drawdown_pct", 100) or 100
    if sharpe > THRESH_SHARPE and mdd < THRESH_MAXDD:
        return True, f"PASS sharpe={sharpe:.2f} mdd={mdd:.1f}%"
    return False, (
        f"未達標: sharpe={sharpe:.2f} (需>{THRESH_SHARPE}) "
        f"mdd={mdd:.1f}% (需<{THRESH_MAXDD})"
    )


def step5_store(spec: dict, res: dict, passed: bool, symbol: str, tf: str):
    """合格寫入 db (標記 agent_pass)"""
    if not passed:
        return
    log = os.path.join(ROOT, "research", "agent_passed.jsonl")
    with open(log, "a") as f:
        f.write(json.dumps({
            "name": spec.get("name"),
            "symbol": symbol, "tf": tf,
            "sharpe": res.get("full_backtest", {}).get("sharpe"),
            "mdd": res.get("full_backtest", {}).get("max_drawdown_pct"),
            "oos_sharpe": res.get("walk_forward", {}).get("avg_oos_sharpe"),
            "ts": datetime.datetime.now().isoformat(),
        }, ensure_ascii=False) + "\n")
    print(f"  [stored] {spec.get('name')} → research/agent_passed.jsonl")


def mutate(spec: dict, feedback: str) -> dict:
    """下一輪變異: 把失敗日誌回傳 LLM 修正 params/logic"""
    return spec  # step1_generate 會吃 feedback 重新生成


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rounds", type=int, default=3)
    ap.add_argument("--symbol", default=SYMBOL_DEF)
    ap.add_argument("--tf", default=TF_DEF)
    args = ap.parse_args()

    print(f"=== agent_loop start: {args.rounds} rounds, {args.symbol} {args.tf} ===")
    feedback = None
    for i in range(1, args.rounds + 1):
        t0 = time.time()
        print(f"\n--- ROUND {i} ({time.time()-t0:.0f}s) ---")
        # 1. 生成
        spec = step1_generate(i, feedback)
        print(f"  [1] LLM spec: {spec.get('name')} | {spec.get('rationale','')[:60]}")
        # 2. 轉譯
        py = step2_translate(spec)
        print(f"  [2] generated: {os.path.basename(py)}")
        # 3. 回測
        res = step3_backtest(py, args.symbol, args.tf)
        print(f"  [3] backtest: {res.get('_elapsed','?')}s rc={res.get('_returncode')}")
        # 4. 過濾
        passed, msg = step4_filter(res)
        print(f"  [4] filter: {msg}")
        # 5. 儲存
        step5_store(spec, res, passed, args.symbol, args.tf)
        feedback = msg if not passed else None
        print(f"  round {i} done in {time.time()-t0:.0f}s")
    print("=== agent_loop complete ===")


if __name__ == "__main__":
    main()
