# AUTO-GENERATED by agent_loop.py round 2026-07-22T06:02:22.207799
from __future__ import annotations
from typing import Any, Optional
import numpy as np
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

def _rsi_series(x: pd.Series) -> float:
    delta = x.diff()
    gain = delta.clip(lower=0).sum()
    loss = (-delta.clip(upper=0)).sum()
    rs = gain / (loss + 1e-9)
    return 100 - 100 / (1 + rs)

class r71342_40075(StrategyBase):
    name = "agent_r71342_40075"
    description = "上一轮均值回归策略在样本外遭遇强趋势导致夏普比率为负。本轮改用趋势跟随逻辑，选用QQE指标，它通过平滑RSI并引入动态因子，能有效过滤震荡市场的假突破。设定60"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().__init__()
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._i = 0
        self._bars: list[Bar] = []
        self._df = pd.DataFrame()
        self._f = None

    def next(self, bar: Bar) -> Optional[Signal]:
        self._bars.append(bar)
        self._i += 1
        if len(self._bars) < self.n + 2:
            return None
        # 每根用累積歷史重算因子 (向量化, 只用歷史無泄漏)
        self._df = pd.DataFrame({
            "close": [b.close for b in self._bars],
            "high": [b.high for b in self._bars],
            "low": [b.low for b in self._bars],
            "volume": [b.volume for b in self._bars],
        })
        try:
            try:
                self._f = self._df.ta.qqe_14_5_4.236_rsima(length=self.n) if hasattr(self._df.ta, 'qqe_14_5_4.236_rsima') else self._df['close'].rolling(self.n).mean()
            except Exception:
                self._f = self._df['close'].rolling(self.n).mean()
            val = self._f.iloc[self._i] if hasattr(self, '_f') and self._i < len(self._f) else None
            qqe_14_5_4.236_rsima = val
        except Exception:
            return None
        if val is None or (isinstance(val, float) and np.isnan(val)):
            return None
        # entry: QQE_14_5_4.236_RSIMA > 60
        # exit: QQE_14_5_4.236_RSIMA < 40
        try:
            if (QQE_14_5_4.236_RSIMA > 60) and self._pos == 0:
                self._pos = 1
                return Signal(action="buy", price=bar.close)
            if (QQE_14_5_4.236_RSIMA < 40) and self._pos == 1:
                self._pos = 0
                return Signal(action="close")
        except Exception:
            return None
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
