# AUTO-GENERATED by agent_loop.py round 2026-07-22T06:19:50.693395
from __future__ import annotations
from typing import Any, Optional
import numpy as np
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

def _rsi_series(x: pd.Series) -> float:
    delta = x.diff()
    gain = delta.clip(lower=0).sum()
    loss = (-delta.clip(upper=0)).sum()
    rs = gain / (loss + 1e-9)
    return 100 - 100 / (1 + rs)

class r72390_03860(StrategyBase):
    name = "agent_r72390_03860"
    description = "The previous 100% MDD indicates severe drawdown likely from trend-following whip"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().__init__()
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._i = 0
        self._bars: list[Bar] = []
        self._df = pd.DataFrame()
        self._f = None

    def next(self, bar: Bar) -> Optional[Signal]:
        self._bars.append(bar)
        self._i += 1
        if len(self._bars) < self.n + 2:
            return None
        # 每根用累積歷史重算因子 (向量化, 只用歷史無泄漏)
        self._df = pd.DataFrame({
            "close": [b.close for b in self._bars],
            "high": [b.high for b in self._bars],
            "low": [b.low for b in self._bars],
            "volume": [b.volume for b in self._bars],
        })
        try:
            delta = self._df['close'].diff()
            gain = delta.clip(lower=0).rolling(self.n).mean()
            loss = (-delta.clip(upper=0)).rolling(self.n).mean()
            rs = gain / (loss + 1e-9)
            self._f = 100 - 100 / (1 + rs)
            val = self._f.iloc[self._i - 1] if self._i - 1 < len(self._f) else None
            rsi = val
        except Exception:
            return None
        if val is None or (isinstance(val, float) and np.isnan(val)):
            return None
        # entry: rsi < 30
        # exit: rsi > 70
        try:
            if (rsi < 30) and self._pos == 0:
                self._pos = 1
                return Signal(action="buy", price=bar.close)
            if (rsi > 70) and self._pos == 1:
                self._pos = 0
                return Signal(action="close")
        except Exception:
            return None
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
