# AUTO-GENERATED by agent_loop.py round 2026-07-23T02:53:57.290764
from __future__ import annotations
from typing import Any, Optional
import numpy as np
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

def _rsi_series(x: pd.Series) -> float:
    delta = x.diff()
    gain = delta.clip(lower=0).sum()
    loss = (-delta.clip(upper=0)).sum()
    rs = gain / (loss + 1e-9)
    return 100 - 100 / (1 + rs)

class r46437_30446(StrategyBase):
    name = "agent_r46437_30446"
    description = "上一轮OOS夏普为负表明存在严重的阈值过拟合。本轮放弃寻找极值阈值，改用MACD柱状图的零轴交叉作为动量反转信号。零轴是天然的物理意义分界线，无需参数优化，能最"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().__init__()
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._i = 0
        self._bars: list[Bar] = []
        self._df = pd.DataFrame()
        self._f = None

    def next(self, bar: Bar) -> Optional[Signal]:
        self._bars.append(bar)
        self._i += 1
        if len(self._bars) < self.n + 2:
            return None
        # 每根用累積歷史重算因子 (向量化, 只用歷史無泄漏)
        self._df = pd.DataFrame({
            "close": [b.close for b in self._bars],
            "high": [b.high for b in self._bars],
            "low": [b.low for b in self._bars],
            "volume": [b.volume for b in self._bars],
        })
        try:
            self._f = self._df.ta.macd(length=self.n).iloc[:, 0]
            val = self._f.iloc[self._i - 1] if self._i - 1 < len(self._f) else None
            macdh_12_26_9 = val
        except Exception:
            return None
        if val is None or (isinstance(val, float) and np.isnan(val)):
            return None
        # entry: MACDh_12_26_9 > 0
        # exit: MACDh_12_26_9 < 0
        try:
            if (MACDh_12_26_9 > 0) and self._pos == 0:
                self._pos = 1
                return Signal(action="buy", price=bar.close)
            if (MACDh_12_26_9 < 0) and self._pos == 1:
                self._pos = 0
                return Signal(action="close")
        except Exception:
            return None
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
