# AUTO-GENERATED by agent_loop.py round 2026-07-24T06:23:10.098492
from __future__ import annotations
from typing import Any, Optional
import numpy as np
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

def _rsi_series(x: pd.Series) -> float:
    delta = x.diff()
    gain = delta.clip(lower=0).sum()
    loss = (-delta.clip(upper=0)).sum()
    rs = gain / (loss + 1e-9)
    return 100 - 100 / (1 + rs)

class r45390_02816(StrategyBase):
    name = "agent_r45390_02816"
    description = "上一轮因阈值设置不当或因子选择导致无交易或深度套牢。Connors RSI专为短期均值回归设计，<15代表极度超卖，>65代表均值回归完成，快速止盈可有效控制M"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().__init__()
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._i = 0
        self._bars: list[Bar] = []
        self._df = pd.DataFrame()
        self._f = None

    def next(self, bar: Bar) -> Optional[Signal]:
        self._bars.append(bar)
        self._i += 1
        if len(self._bars) < self.n + 2:
            return None
        # 每根用累積歷史重算因子 (向量化, 只用歷史無泄漏)
        self._df = pd.DataFrame({
            "close": [b.close for b in self._bars],
            "high": [b.high for b in self._bars],
            "low": [b.low for b in self._bars],
            "volume": [b.volume for b in self._bars],
        })
        try:
            try:
                self._f = self._df.ta.crsi(length=self.n) if hasattr(self._df.ta, 'crsi') else self._df['close'].rolling(self.n).mean()
            except Exception:
                self._f = self._df['close'].rolling(self.n).mean()
            val = self._f.iloc[self._i] if hasattr(self, '_f') and self._i < len(self._f) else None
            crsi = val
        except Exception:
            return None
        if val is None or (isinstance(val, float) and np.isnan(val)):
            return None
        # entry: crsi < 15
        # exit: crsi > 65
        try:
            if (crsi < 15) and self._pos == 0:
                self._pos = 1
                return Signal(action="buy", price=bar.close)
            if (crsi > 65) and self._pos == 1:
                self._pos = 0
                return Signal(action="close")
        except Exception:
            return None
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
