# AUTO-GENERATED by agent_loop.py round 2026-07-22T07:34:29.783534
from __future__ import annotations
from typing import Any, Optional
import numpy as np
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

def _rsi_series(x: pd.Series) -> float:
    delta = x.diff()
    gain = delta.clip(lower=0).sum()
    loss = (-delta.clip(upper=0)).sum()
    rs = gain / (loss + 1e-9)
    return 100 - 100 / (1 + rs)

class r76869_02442(StrategyBase):
    name = "agent_r76869_02442"
    description = "上一轮OOS失效通常源于均值回归在单边市的失效或震荡指标频繁翻转导致的摩擦成本。STCmacd结合了MACD的趋势追踪与随机指标的周期平滑，60/40的非对称阈"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().__init__()
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._i = 0
        self._bars: list[Bar] = []
        self._df = pd.DataFrame()
        self._f = None

    def next(self, bar: Bar) -> Optional[Signal]:
        self._bars.append(bar)
        self._i += 1
        if len(self._bars) < self.n + 2:
            return None
        # 每根用累積歷史重算因子 (向量化, 只用歷史無泄漏)
        self._df = pd.DataFrame({
            "close": [b.close for b in self._bars],
            "high": [b.high for b in self._bars],
            "low": [b.low for b in self._bars],
            "volume": [b.volume for b in self._bars],
        })
        try:
            try:
                self._f = self._df.ta.stcmacd_10_12_26_0.5(length=self.n) if hasattr(self._df.ta, 'stcmacd_10_12_26_0.5') else self._df['close'].rolling(self.n).mean()
            except Exception:
                self._f = self._df['close'].rolling(self.n).mean()
            val = self._f.iloc[self._i] if hasattr(self, '_f') and self._i < len(self._f) else None
            stcmacd_10_12_26_0.5 = val
        except Exception:
            return None
        if val is None or (isinstance(val, float) and np.isnan(val)):
            return None
        # entry: STCmacd_10_12_26_0.5 > 60
        # exit: STCmacd_10_12_26_0.5 < 40
        try:
            if (STCmacd_10_12_26_0.5 > 60) and self._pos == 0:
                self._pos = 1
                return Signal(action="buy", price=bar.close)
            if (STCmacd_10_12_26_0.5 < 40) and self._pos == 1:
                self._pos = 0
                return Signal(action="close")
        except Exception:
            return None
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
