# AUTO-GENERATED by agent_loop.py round 2026-07-24T05:28:15.499519
from __future__ import annotations
from typing import Any, Optional
import numpy as np
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

def _rsi_series(x: pd.Series) -> float:
    delta = x.diff()
    gain = delta.clip(lower=0).sum()
    loss = (-delta.clip(upper=0)).sum()
    rs = gain / (loss + 1e-9)
    return 100 - 100 / (1 + rs)

class r42095_91537(StrategyBase):
    name = "agent_r42095_91537"
    description = "上一轮OOS夏普为负表明存在过拟合或趋势跟踪在震荡市失效。Connors RSI结合了短期动量与均值回归特性，阈值10和70是经典统计边界，能有效过滤噪音，降低"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().__init__()
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._i = 0
        self._bars: list[Bar] = []
        self._df = pd.DataFrame()
        self._f = None

    def next(self, bar: Bar) -> Optional[Signal]:
        self._bars.append(bar)
        self._i += 1
        if len(self._bars) < self.n + 2:
            return None
        # 每根用累積歷史重算因子 (向量化, 只用歷史無泄漏)
        self._df = pd.DataFrame({
            "close": [b.close for b in self._bars],
            "high": [b.high for b in self._bars],
            "low": [b.low for b in self._bars],
            "volume": [b.volume for b in self._bars],
        })
        try:
            try:
                self._f = self._df.ta.crsi(length=self.n) if hasattr(self._df.ta, 'crsi') else self._df['close'].rolling(self.n).mean()
            except Exception:
                self._f = self._df['close'].rolling(self.n).mean()
            val = self._f.iloc[self._i] if hasattr(self, '_f') and self._i < len(self._f) else None
            crsi = val
        except Exception:
            return None
        if val is None or (isinstance(val, float) and np.isnan(val)):
            return None
        # entry: crsi < 10
        # exit: crsi > 70
        try:
            if (crsi < 10) and self._pos == 0:
                self._pos = 1
                return Signal(action="buy", price=bar.close)
            if (crsi > 70) and self._pos == 1:
                self._pos = 0
                return Signal(action="close")
        except Exception:
            return None
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
