# AUTO-GENERATED by agent_loop.py round 2026-07-21T01:22:30.836722
from __future__ import annotations
from typing import Any, Optional
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

class r68150_78826(StrategyBase):
    name = "agent_r68150_78826"
    description = "布林带收窄预示波动率压缩，突破时配合成交量放大可确认趋势启动。RSI过滤过度超买信号，ATR动态止损适应市场波动变化，MACD交叉验证趋势延续性。该组合在趋势行"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().init(params)
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._closes: list[float] = []

    def next(self, bar: Bar) -> Optional[Signal]:
        self._closes.append(bar.close)
        if len(self._closes) < self.n + 2:
            return None
        s = pd.Series(self._closes)
        # indicators: ['BBANDS', 'ATR', 'RSI', 'MACD']
        delta = s.diff()
        gain = delta.clip(lower=0).rolling(self.n).sum()
        loss = (-delta.clip(upper=0)).rolling(self.n).sum()
        rs = gain / (loss + 1e-9)
        rsi = (100 - 100 / (1 + rs)).iloc[-1]
        if pd.isna(rsi):
            return None
        # entry: 当价格突破布林带上轨且RSI<70，同时当前ATR小于过去20周期ATR中位数的80%
        # exit: 当价格跌破1.5倍ATR动态止损位或MACD下穿信号线
        if rsi < 30 and self._pos == 0:
            self._pos = 1
            return Signal(action="buy", price=bar.close)
        if rsi > 70 and self._pos == 1:
            self._pos = 0
            return Signal(action="close")
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
