# AUTO-GENERATED by agent_loop.py round 2026-07-21T08:19:53.120311
from __future__ import annotations
from typing import Any, Optional
import pandas as pd
from strategies.base import Bar, Signal, StrategyBase

class r93193_20774(StrategyBase):
    name = "agent_r93193_20774"
    description = "RSI 低於 30 時表示超賣，高於 70 時表示超買，根據均值回歸理論，超賣時買入，超買時賣出"
    category = "agent"

    def init(self, params: dict[str, Any]) -> None:
        super().init(params)
        self.n = int(params.get("n", 14))
        self._pos = 0
        self._closes: list[float] = []

    def next(self, bar: Bar) -> Optional[Signal]:
        self._closes.append(bar.close)
        if len(self._closes) < self.n + 2:
            return None
        s = pd.Series(self._closes)
        # indicators: ['RSI']
        delta = s.diff()
        gain = delta.clip(lower=0).rolling(self.n).sum()
        loss = (-delta.clip(upper=0)).rolling(self.n).sum()
        rs = gain / (loss + 1e-9)
        rsi = (100 - 100 / (1 + rs)).iloc[-1]
        if pd.isna(rsi):
            return None
        # entry: RSI < 30
        # exit: RSI > 70
        if rsi < 30 and self._pos == 0:
            self._pos = 1
            return Signal(action="buy", price=bar.close)
        if rsi > 70 and self._pos == 1:
            self._pos = 0
            return Signal(action="close")
        return None

    def get_params_space(self) -> dict[str, Any]:
        return {"n": {"type": "range", "min": 5, "max": 50, "step": 1}}

    def warmup_period(self) -> int:
        return self.n + 2
