[theme]
primaryColor = "#00C9FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
enableCORS = false
enableXsrfProtection = false
