[theme]
primaryColor = "#2962FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
